### ISSUE TITLE
eredis incompatible with Elixir 1.15

### ISSUE THREAD

**Issue by Sgoettschkes** [launchdarkly/erlang-server-sdk#80]
**Describe the bug**
When upgrading to Elixir 1.15 (this applies to all released versions of 1.15, so 1.15.0, 1.15.1, and 1.15.2), the dependencies cannot be compiled anymore because `eredis` fails with the following error:

```
==> eredis
Compiling 6 files (.erl)
src/eredis_parser.erl:25:14: can't find include lib "eunit/include/eunit.hrl"
%   25| -include_lib("eunit/include/eunit.hrl").
%     |              ^
```

**To reproduce**
With Elixir 1.15 (and Erlang 25 or 26) and `{:ldclient, "~> 2.0.0", hex: :launchdarkly_server_sdk},` in your `mix.exs` dependencies, run `mix deps.compile`

**Expected behavior**
The dependencies should compile

**SDK version**
2.0.5

**Language version, developer tools**
Elixir 1.15, Erlang/OTP 25

**Additional context**
The error was reported to `eredis` and is already fixed in main: https://github.com/Nordix/eredis/issues/79 After they release a new version, the `ldclient` can use this version in their dependencies, fixing this issue.

As a short-term fix, adding this to the dependencies will fix the issue:

```
{
        :eredis,
        git: "https://github.com/Nordix/eredis.git",
        ref: "2dee4054629d9a7b0576e6aa4799e3dea9cf4e7c",
        override: true
      },
```

I am also wondering if there is a way to mark dependencies as optional in Erlang. It's possible in Elixir and would solve this problem for us since we do not use Redis.

**Comment by kinyoklion** [comment]
Hello @Sgoettschkes,

Thank you for reporting the issue. Will take a look. 

_Filed internally as 208867_

Thank you,
Ryan

**Comment by fcevado** [comment]
@Sgoettschkes you can deal with that forcing `eredis` to use rebar. if you add `{:eredis, manager: :rebar3}` to your supervision tree it should work.

**Comment by Sgoettschkes** [comment]
Thanks @fcevado, that works. Running it locally (with mix) works, but after a release is built, the LaunchDarkly GenServer seems to throw errors. I'll look into this and report back if this is indeed a problem with this library or if it's something in our code.

**Comment by pdgonzalez872** [comment]
@kinyoklion and @Sgoettschkes, adding some context here as we have an Elixir app that has this lib in a `mix.exs`.

My test case was getting a `mix deps.get && mix compile && mix test` run successfully. The OG issue above is solved by updating eredis to 1.7.1, here is a PR doing this bump if it helps(https://github.com/launchdarkly/erlang-server-sdk/pull/92) , but the diff is:

```diff
erlang-server-sdk [main] $ git diff
diff --git a/rebar.config b/rebar.config
index 934d0a2..d9de1f8 100644
--- a/rebar.config
+++ b/rebar.config
@@ -5,7 +5,7 @@
   {verl, "1.0.1"},
   {lru, "2.4.0"},
   {uuid, "2.0.2", {pkg, uuid_erl}},
-  {eredis, "1.4.0"},
+  {eredis, "1.7.1"},
   {yamerl, "0.10.0"},
   {certifi, "2.10.0"}
 ]}.
erlang-server-sdk [main] $
```

Then, we use `path` in our app when configuring the dep. After doing this and having redis up locally, my test case (the commands above) does work (all commands succeed).

**Comment by Sgoettschkes** [comment]
@fcevado It seems that after the changes to the eredis dependency, the ldclient works with Elixir 1.15 and OTP 25. We still have a problem as soon as we try to upgrade to OTP 26, but this might be unrelated to this library.
